spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/Prokat_avto"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/Prokat_avto"
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
